# GCP ML Engineer Project Configuration

gcp:
  project_id: ml-engineer-study-462417
  region: us-central1
  zone: us-central1-a

storage:
  bucket_name: ${project_id}-ml-artifacts
  data_path: data/
  model_path: models/
  pipeline_path: pipelines/

bigquery:
  dataset_id: ml_datasets
  location: US

vertex_ai:
  endpoint_region: us-central1
  prediction_region: us-central1
  training_region: us-central1

compute:
  machine_type: n1-standard-4
  accelerator_type: NVIDIA_TESLA_T4
  accelerator_count: 1
